services:
  - type: web
    name: musicbot-backend
    runtime: java
    buildCommand: "./gradlew clean build"
    startCommand: "java -jar build/libs/musicbot-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: "17"

  - type: static
    name: musicbot-frontend
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/dist"